name: Weather
description: New sample weather flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  sleek_circular_slider: ^2.0.1
  r_dotted_line_border: ^0.1.1
  flutter_zoom_drawer: ^2.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.1.6

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/launcher_icon/launcher_icon.png
  image_path_ios: assets/launcher_icon/launcher_icon.png

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  image: assets/launcher_icon/launcher_icon_4x.png
  color_dark: "#2F2F2F"
  image_dark: assets/launcher_icon/launcher_icon_4x.png
  android_gravity: center
  ios_content_mode: center
  web_imae_mode: center
  android12: true

flutter:
  uses-material-design: true

  assets:
    - assets/launcher_icon/launcher_icon.png
    - assets/weathers/
    - assets/icons/

  fonts:
    - family: MohrRounded
      fonts:
        - asset: assets/fonts/MohrRounded-Light.ttf
        - asset: assets/fonts/MohrRounded-Regular.ttf
        - asset: assets/fonts/MohrRounded-Medium.ttf
        - asset: assets/fonts/MohrRounded-SemiBold.ttf
        - asset: assets/fonts/MohrRounded-Bold.ttf
        - asset: assets/fonts/MohrRounded-Thin.ttf