name: weather
description: New sample weather flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  sleek_circular_slider: ^2.0.1
  r_dotted_line_border: ^0.1.1
  flutter_zoom_drawer: ^2.3.1+1
  logging: ^1.0.1
  freezed_annotation: ^2.0.1
  json_annotation: ^4.4.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  flare_flutter: ^3.0.2
  dio: ^4.0.6
  hive: ^2.0.4
  intl: ^0.17.0
  dartz: ^0.10.1
  get_it: ^7.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.1.6
  json_serializable: ^6.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.2
  hive_generator: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/launcher_icon/launcher_icon.png
  image_path_ios: assets/launcher_icon/launcher_icon.png

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  image: assets/launcher_icon/launcher_icon_4x.png
  color_dark: "#2F2F2F"
  image_dark: assets/launcher_icon/launcher_icon_4x.png
  android_gravity: center
  ios_content_mode: center
  web_imae_mode: center
  android12: true

flutter:
  uses-material-design: true

  assets:
    - assets/launcher_icon/launcher_icon.png
    - assets/weathers/
    - assets/icons/
    - assets/loading_anim_orange.flr

  fonts:
    - family: MohrRounded
      fonts:
        - asset: assets/fonts/MohrRounded-Thin.ttf
          weight: 100
        - asset: assets/fonts/MohrRounded-Light.ttf
          weight: 300
        - asset: assets/fonts/MohrRounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/MohrRounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/MohrRounded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MohrRounded-Bold.ttf
          weight: 700
